version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: ${APP_PORT:-3000}
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      JWT_SECRET: ${JWT_SECRET}
      APP_PORT: ${APP_PORT}
      TYPEORM_CONNECTION: "mysql"
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: "admin"
      TYPEORM_PASSWORD: "admin"
      TYPEORM_DATABASE: "movies"
      TYPEORM_PORT: "3306"
      TYPEORM_ENTITIES: "src/**/*.entity.{.ts,.js}"
      TYPEORM_SEEDING_FACTORIES: "src/factories/**/*{.ts,.js}"
      TYPEORM_SEEDING_SEEDS: "src/seeds/**/*{.ts,.js}"

  mysql:
    image: "mysql:5.7.24"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "movies"
